---
openapi: 3.1.0
info:
  title: Candy Delivery API
  version: '1.0'
paths:
  "/api/login":
    post:
      tags:
      - auth
      summary: Login
      operationId: login_api_login_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserLogin"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TokenResponse"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/couriers":
    get:
      summary: Get All Couriers
      operationId: get_all_couriers_couriers_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
    post:
      summary: Import Couriers
      operationId: import_couriers_couriers_post
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: true
              type: object
              title: Req
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/couriers/{courier_id}":
    patch:
      summary: Update Courier
      operationId: update_courier_couriers__courier_id__patch
      parameters:
      - name: courier_id
        in: path
        required: true
        schema:
          type: integer
          title: Courier Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CourierUpdateRequest"
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
    get:
      summary: Get Courier
      operationId: get_courier_couriers__courier_id__get
      parameters:
      - name: courier_id
        in: path
        required: true
        schema:
          type: integer
          title: Courier Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/couriers/{courier_id}/orders":
    get:
      summary: Get Courier Orders
      operationId: get_courier_orders_couriers__courier_id__orders_get
      parameters:
      - name: courier_id
        in: path
        required: true
        schema:
          type: integer
          title: Courier Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/orders":
    get:
      summary: Get All Orders
      operationId: get_all_orders_orders_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
    post:
      summary: Import Orders
      operationId: import_orders_orders_post
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: true
              type: object
              title: Req
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/orders/assign":
    post:
      summary: Assign Orders
      operationId: assign_orders_orders_assign_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/OrdersAssignPostRequest"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/orders/complete":
    post:
      summary: Complete Order
      operationId: complete_order_orders_complete_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/OrdersCompletePostRequest"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/orders/{order_id}/cancel":
    patch:
      summary: Cancel Order
      operationId: cancel_order_orders__order_id__cancel_patch
      parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          title: Order Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/orders/{order_id}":
    delete:
      summary: Delete Order
      description: Удаление заказа администратором
      operationId: delete_order_orders__order_id__delete
      parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          title: Order Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    CourierUpdateRequest:
      properties:
        courier_type:
          anyOf:
          - type: string
          - type: 'null'
          title: Courier Type
        regions:
          anyOf:
          - items:
              type: integer
            type: array
          - type: 'null'
          title: Regions
        working_hours:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: Working Hours
      type: object
      title: CourierUpdateRequest
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    OrdersAssignPostRequest:
      properties:
        courier_id:
          type: integer
          exclusiveMinimum: 0
          title: Courier Id
      type: object
      required:
      - courier_id
      title: OrdersAssignPostRequest
    OrdersCompletePostRequest:
      properties:
        courier_id:
          type: integer
          exclusiveMinimum: 0
          title: Courier Id
        order_id:
          type: integer
          exclusiveMinimum: 0
          title: Order Id
        complete_time:
          type: string
          title: Complete Time
      type: object
      required:
      - courier_id
      - order_id
      - complete_time
      title: OrdersCompletePostRequest
    TokenResponse:
      properties:
        access_token:
          type: string
          title: Access Token
        token_type:
          type: string
          title: Token Type
        role:
          type: string
          title: Role
        courier_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Courier Id
      type: object
      required:
      - access_token
      - token_type
      - role
      title: TokenResponse
    UserLogin:
      properties:
        username:
          type: string
          title: Username
        password:
          type: string
          title: Password
      type: object
      required:
      - username
      - password
      title: UserLogin
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
